### Bài 1: Tạo Tensor cơ bản

- Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả. 

In [2]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


- Kích thước: torch.Size([2, 3
])
- Số chiều: 2
- Kiểu dữ liệu: torch.int32

### Bài 2. Tạo các Tensor thường dùng

In [3]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.3909, 0.1915, 0.1406, 0.0402],
        [0.9720, 0.0732, 0.0730, 0.2706],
        [0.0390, 0.1826, 0.1592, 0.6143]])
tensor([[-0.6658,  0.2461, -0.6546, -0.1098],
        [ 0.0338,  0.6636, -0.1240, -0.8313],
        [ 0.9715, -0.2650,  2.0978,  1.2367]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


- Phân biệt torch.rand() và torch.randn():
    - torch.rand(): Sinh các số ngẫu nhiên theo phân bố đều (Uniform distribution) trong khoảng $[0, 1)$
    - torch.randn(): Sinh các số ngẫu nhiên theo phân bố chuẩn (Standard Normal distribution) với trung bình $\mu = 0$ và độ lệch chuẩn $\sigma = 1$.

- Tạo thêm một Tensor 5 × 5 chứa toàn giá trị 10.

In [4]:
tensor_10 = torch.full((5, 5), 10.0)

### Bài 3. Kiểm tra thông tin Tensor

In [5]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


- Ý nghĩa của torch.Size([2, 3, 4]): Tensor này có 3 chiều 
    - Chiều thứ nhất (ngoài cùng) có kích thước 2
    - Chiều thứ hai có kích thước 3
    - Chiều thứ ba (trong cùng) có kích thước 4. Tổng số phần tử là $2 \times 3 \times 4 = 24$ phần tử.

### Bài 4. Slicing và Indexing

In [6]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")

Original tensor:
tensor([[[-1.5913, -1.7776,  1.1727, -0.7592,  0.4511],
         [-0.6775,  0.8426,  0.1964,  0.0640, -0.4083],
         [-0.9480, -0.0683, -0.6484, -0.4980,  0.3161],
         [ 0.5351, -0.3228,  0.4332,  1.2454, -0.3890]],

        [[ 0.0137,  1.0884, -0.3422, -1.3438, -1.7520],
         [ 1.2690,  1.1892, -0.1936, -2.1161, -0.6432],
         [ 0.6476,  0.3038, -2.2542, -1.2135, -0.3133],
         [-0.4568, -0.9948,  0.8151,  0.1202, -1.2508]],

        [[ 2.0466, -0.8842, -1.3283,  1.2651, -2.0476],
         [ 2.1170, -0.1483,  1.1726,  0.4541,  0.2844],
         [ 0.4497, -0.8435, -0.2215, -0.8290, -0.7926],
         [ 0.3510, -0.2177,  0.4754,  1.0648,  0.0721]]])

Tensor a[1]:
tensor([[ 0.0137,  1.0884, -0.3422, -1.3438, -1.7520],
        [ 1.2690,  1.1892, -0.1936, -2.1161, -0.6432],
        [ 0.6476,  0.3038, -2.2542, -1.2135, -0.3133],
        [-0.4568, -0.9948,  0.8151,  0.1202, -1.2508]])

Tensor a[1:, 2:4]:


- Shape a[1]: torch.Size([4, 5])
- Shape a[1:, 2:4]: torch.Size([2, 2, 5])
- Lấy hai phần tử cuối cùng trên chiều thứ ba:
 sub_tensor = a[:, :, -2:]

### Bài 5. Reshape và Flatten

In [7]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[ 1.3930, -0.2094, -0.3693,  0.2044],
        [ 0.8569, -0.7402, -0.3956, -0.1006],
        [ 1.3586,  0.1656, -0.4912,  0.0999]])

Flatten:
tensor([ 1.3930, -0.2094, -0.3693,  0.2044,  0.8569, -0.7402, -0.3956, -0.1006,
         1.3586,  0.1656, -0.4912,  0.0999])

Reshape to 3 x 2 x 2:
tensor([[[ 1.3930, -0.2094],
         [-0.3693,  0.2044]],

        [[ 0.8569, -0.7402],
         [-0.3956, -0.1006]],

        [[ 1.3586,  0.1656],
         [-0.4912,  0.0999]]])


- Trước và sau khi reshape, số phần tử luôn bằng 12.

- Reshape thành $2 \times 6$:

In [15]:
a.reshape(2, 6)

tensor([[-0.2607,  1.1033, -0.3694,  0.2684, -0.1848,  1.4147],
        [ 1.9205,  0.8780,  0.3023,  1.0981,  2.0876,  1.6182]])

### Bài 6. Phép toán và nhân ma trận

In [8]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[-0.3704, -0.9766, -1.0216],
        [ 0.3675, -0.0587, -0.2544]])
b:
tensor([[ 0.0675, -1.0760, -0.5493],
        [ 1.3792, -0.8578, -0.0243]])

a + b:
tensor([[-0.3029, -2.0526, -1.5708],
        [ 1.7467, -0.9166, -0.2787]])

a / b:
tensor([[-5.4862,  0.9076,  1.8599],
        [ 0.2665,  0.0685, 10.4901]])

a^2:
tensor([[0.1372, 0.9538, 1.0436],
        [0.1351, 0.0034, 0.0647]])

Matrix multiplication:
tensor([[1.5869, 0.3516],
        [0.2277, 0.5634]])


- Phân biệt a * b và a @ b.T:
    - a * b: Là phép nhân từng phần tử tương ứng (element-wise multiplication) giữa hai Tensor cùng kích thước.
    - a @ b.T: Là phép nhân ma trận (matrix multiplication).  
- Shape của a @ b.T:
Vì a có shape $(2, 3)$ và b.T có shape $(3, 2)$, kết quả sẽ có shape là torch.Size([2, 2])

### Bài 7. Các hàm thống kê trên Tensor

In [18]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=1))
print("\nStandard deviation:")
print(torch.std(a, dim=1))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=1))

tensor([[ 0.0152, -0.8548, -0.4039, -0.2617],
        [-0.9401,  0.5650,  2.0802, -0.6708],
        [-0.5114, -0.9704,  0.7087, -0.0746]])

Mean:
tensor([-0.3763,  0.2586, -0.2119])

Standard deviation:
tensor([0.3634, 1.3799, 0.7145])

Cumulative sum:
tensor([[ 0.0152, -0.8396, -1.2434, -1.5051],
        [-0.9401, -0.3750,  1.7052,  1.0344],
        [-0.5114, -1.4818, -0.7731, -0.8477]])


- Tham số dim=0 ép xẹp chiều 0 (tính trung bình/độ lệch chuẩn theo hàng, kết quả trả về theo từng cột)

### Bài 8. Autograd cơ bản

In [10]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


- Đạo hàm lý thuyết $y' = 2x = 2 \times 3.6 = 7.2$, khớp hoàn toàn với kết quả Autograd. 
- Với hàm bậc 2 mới, $y' = 6x + 2 = 6(3.6) + 2 = 23.6$,Autograd tính chính xác giá trị đạo hàm. 

### Bài 9. Gradient Descent tìm hệ số đa thức

In [11]:
import numpy as np
import torch

polynomial = np.poly1d([1, 2, 3])
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-0.5426],
        [-3.0178],
        [-1.5344]], requires_grad=True)
Learned coefficients:
tensor([[1.0499],
        [1.6808],
        [0.8617]], requires_grad=True)


Hệ số học được hội tụ chính xác về [1, 2, 3] của đa thức ban đầu.  
- optimizer.zero_grad() xóa bộ nhớ đệm đạo hàm cũ.  
- mse.backward() tính gradient thông qua lan truyền ngược.  
- optimizer.step() cập nhật trọng số w theo giải thuật NAdam. 

### Bài 10. Giải hệ phương trình bằng Autograd

In [12]:
import random
import torch

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4

    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
    
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.5559, requires_grad=True)
B = tensor(4.4440, requires_grad=True)
C = tensor(3.4441, requires_grad=True)
D = tensor(2.4440, requires_grad=True)


- Hệ phương trình bậc nhất 4 ẩn này có phụ thuộc tuyến tính (thỏa mãn $y1 - y2 = y3 - y4$).
- Vì số phương trình độc lập ít hơn số ẩn nên hệ bài toán có vô số nghiệm. Tùy vào giá trị khởi tạo ban đầu mà mô hình sẽ tối ưu về các bộ nghiệm khác nhau.

### Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau:

- Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.

- Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.


- Cho y = 2x2 + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.

- Thay đa thức trong Bài 9 bằng y = 2x2 - 3x + 5; huấn luyện và cho biết các hệ số tìm được.

In [13]:
import numpy as np
import torch

print("=================== CÂU 1 ===================")
# 1. Tạo Tensor X có 24 phần tử (dùng arange hoặc randn)
X = torch.arange(24)
print("Tensor X ban đầu (24 phần tử):")
print(X)

# Reshape thành 4x6, 2x12 và 2x3x4
X_4x6 = X.reshape(4, 6)
X_2x12 = X.reshape(2, 12)
X_2x3x4 = X.reshape(2, 3, 4)

print("\nReshape 4x6:\n", X_4x6)
print("\nReshape 2x12:\n", X_2x12)
print("\nReshape 2x3x4:\n", X_2x3x4)


print("\n=================== CÂU 2 ===================")
# 2. Tạo hai Tensor A, B kích thước 3x4
A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("Tensor A:\n", A)
print("Tensor B:\n", B)

# Tính các phép toán
print("\nA + B:\n", A + B)
print("\nA * B (element-wise):\n", A * B)
print("\nA / B (element-wise):\n", A / B)

# Trung bình và độ lệch chuẩn theo cột (dim=0) cho A và B
print("\n[A] Trung bình theo cột (dim=0):", torch.mean(A, dim=0))
print("[A] Độ lệch chuẩn theo cột (dim=0):", torch.std(A, dim=0))

print("\n[B] Trung bình theo cột (dim=0):", torch.mean(B, dim=0))
print("[B] Độ lệch chuẩn theo cột (dim=0):", torch.std(B, dim=0))


print("\n=================== CÂU 3 ===================")
# 3. Cho y = 2*x^2 + 5*x + 3. Dùng autograd tính dy/dx tại x = 2
x = torch.tensor(2.0, requires_grad=True)
y = 2 * x**2 + 5 * x + 3

# Tính gradient tự động
y.backward()

print("Giá trị x:", x.item())
print("Giá trị y:", y.item())
print("Gradient dy/dx từ PyTorch (x.grad):", x.grad.item())

# Kiểm tra thủ công:
# y = 2*x^2 + 5*x + 3  =>  dy/dx = 4*x + 5
# Tại x = 2:  dy/dx = 4*(2) + 5 = 13
manual_grad = 4 * 2 + 5
print(f"Kiểm tra thủ công: dy/dx = 4*(2) + 5 = {manual_grad}")
print("Kết quả trùng khớp!" if x.grad.item() == manual_grad else "Kết quả không trùng khớp!")


print("\n=================== CÂU 4 ===================")
# 4. Thay đa thức bài 9 bằng y = 2*x^2 - 3*x + 5
# Sinh dữ liệu từ đa thức mới
polynomial = np.poly1d([2, -3, 5])
N = 20
np.random.seed(42)  # Cố định seed cho kết quả ổn định
X_np = np.random.rand(N, 1) * 5
Y_np = polynomial(X_np)

# Chuẩn bị ma trận đặc trưng XX = [x^2, x, 1]
XX_np = np.hstack([X_np**2, X_np, np.ones_like(X_np)])

# Khởi tạo trọng số w (gồm 3 hệ số cần học)
w = torch.randn(3, 1, requires_grad=True, dtype=torch.float32)
x_tensor = torch.tensor(XX_np, dtype=torch.float32)
y_tensor = torch.tensor(Y_np, dtype=torch.float32)

# Sử dụng optimizer NAdam với learning rate thích hợp
optimizer = torch.optim.NAdam([w], lr=0.1)

print("Hệ số khởi tạo ban đầu:")
print(w.detach().numpy().flatten())

# Vòng lặp huấn luyện
epochs = 3000
for epoch in range(epochs):
    optimizer.zero_grad()
    y_pred = x_tensor @ w
    mse = torch.mean(torch.square(y_tensor - y_pred))
    mse.backward()
    optimizer.step()

learned_coeffs = w.detach().numpy().flatten()
print(f"\nHệ số học được sau {epochs} epoch:")
print(f"a = {learned_coeffs[0]:.4f}, b = {learned_coeffs[1]:.4f}, c = {learned_coeffs[2]:.4f}")
print("Hệ số thực tế ban đầu: [2, -3, 5]")

=================== CÂU 1 ===================
Tensor X ban đầu (24 phần tử):
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

Reshape 4x6:
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

Reshape 2x12:
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

Reshape 2x3x4:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

=================== CÂU 2 ===================
Tensor A:
 tensor([[ 0.3748,  0.3104, -0.9338,  0.4540],
        [ 0.9923, -1.3817, -0.4850, -0.3541],
        [-1.0671, -0.3519,  1.6253,  0.6640]])
Tensor B:
 tensor([[-1.9658,  1.6780, -1.1774, -0.6877],
        [-0.4551, -0.0223,  0.3491,  0.5035],
        [-0.2180, -1.8154, -0.7405, -1.517

- Yêu cầu 3: Đạo hàm lý thuyết $\frac{dy}{dx} = 4x + 5$. Tại $x=2 \implies \frac{dy}{dx} = 4(2) + 5 = 13.0$, khớp tuyệt đối với Autograd.
- Yêu cầu 4: Thuật toán tối ưu NAdam hội tụ thành công về bộ hệ số gốc [2.0, -3.0, 5.0] sau 2500 epoch.